export const uniswapV3PoolABI = [
	{ stateMutability: "nonpayable", type: "constructor", inputs: [] },
	{ type: "error", inputs: [], name: "AI" },
	{ type: "error", inputs: [], name: "AS" },
	{ type: "error", inputs: [], name: "F0" },
	{ type: "error", inputs: [], name: "F1" },
	{ type: "error", inputs: [], name: "I" },
	{ type: "error", inputs: [], name: "IIA" },
	{ type: "error", inputs: [], name: "L" },
	{ type: "error", inputs: [], name: "LO" },
	{ type: "error", inputs: [], name: "LOK" },
	{ type: "error", inputs: [], name: "M0" },
	{ type: "error", inputs: [], name: "M1" },
	{ type: "error", inputs: [], name: "NP" },
	{ type: "error", inputs: [], name: "OLD" },
	{ type: "error", inputs: [], name: "R" },
	{ type: "error", inputs: [], name: "T" },
	{ type: "error", inputs: [], name: "TF" },
	{ type: "error", inputs: [], name: "TLM" },
	{ type: "error", inputs: [], name: "TLU" },
	{ type: "error", inputs: [], name: "TUM" },
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "owner",
				internalType: "address",
				type: "address",
				indexed: true,
			},
			{
				name: "tickLower",
				internalType: "int24",
				type: "int24",
				indexed: true,
			},
			{
				name: "tickUpper",
				internalType: "int24",
				type: "int24",
				indexed: true,
			},
			{
				name: "amount",
				internalType: "uint128",
				type: "uint128",
				indexed: false,
			},
			{
				name: "amount0",
				internalType: "uint256",
				type: "uint256",
				indexed: false,
			},
			{
				name: "amount1",
				internalType: "uint256",
				type: "uint256",
				indexed: false,
			},
		],
		name: "Burn",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "owner",
				internalType: "address",
				type: "address",
				indexed: true,
			},
			{
				name: "recipient",
				internalType: "address",
				type: "address",
				indexed: false,
			},
			{
				name: "tickLower",
				internalType: "int24",
				type: "int24",
				indexed: true,
			},
			{
				name: "tickUpper",
				internalType: "int24",
				type: "int24",
				indexed: true,
			},
			{
				name: "amount0",
				internalType: "uint128",
				type: "uint128",
				indexed: false,
			},
			{
				name: "amount1",
				internalType: "uint128",
				type: "uint128",
				indexed: false,
			},
		],
		name: "Collect",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "sender",
				internalType: "address",
				type: "address",
				indexed: true,
			},
			{
				name: "recipient",
				internalType: "address",
				type: "address",
				indexed: true,
			},
			{
				name: "amount0",
				internalType: "uint128",
				type: "uint128",
				indexed: false,
			},
			{
				name: "amount1",
				internalType: "uint128",
				type: "uint128",
				indexed: false,
			},
		],
		name: "CollectProtocol",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "sender",
				internalType: "address",
				type: "address",
				indexed: true,
			},
			{
				name: "recipient",
				internalType: "address",
				type: "address",
				indexed: true,
			},
			{
				name: "amount0",
				internalType: "uint256",
				type: "uint256",
				indexed: false,
			},
			{
				name: "amount1",
				internalType: "uint256",
				type: "uint256",
				indexed: false,
			},
			{
				name: "paid0",
				internalType: "uint256",
				type: "uint256",
				indexed: false,
			},
			{
				name: "paid1",
				internalType: "uint256",
				type: "uint256",
				indexed: false,
			},
		],
		name: "Flash",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "observationCardinalityNextOld",
				internalType: "uint16",
				type: "uint16",
				indexed: false,
			},
			{
				name: "observationCardinalityNextNew",
				internalType: "uint16",
				type: "uint16",
				indexed: false,
			},
		],
		name: "IncreaseObservationCardinalityNext",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "sqrtPriceX96",
				internalType: "uint160",
				type: "uint160",
				indexed: false,
			},
			{ name: "tick", internalType: "int24", type: "int24", indexed: false },
		],
		name: "Initialize",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "sender",
				internalType: "address",
				type: "address",
				indexed: false,
			},
			{
				name: "owner",
				internalType: "address",
				type: "address",
				indexed: true,
			},
			{
				name: "tickLower",
				internalType: "int24",
				type: "int24",
				indexed: true,
			},
			{
				name: "tickUpper",
				internalType: "int24",
				type: "int24",
				indexed: true,
			},
			{
				name: "amount",
				internalType: "uint128",
				type: "uint128",
				indexed: false,
			},
			{
				name: "amount0",
				internalType: "uint256",
				type: "uint256",
				indexed: false,
			},
			{
				name: "amount1",
				internalType: "uint256",
				type: "uint256",
				indexed: false,
			},
		],
		name: "Mint",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "feeProtocol0Old",
				internalType: "uint8",
				type: "uint8",
				indexed: false,
			},
			{
				name: "feeProtocol1Old",
				internalType: "uint8",
				type: "uint8",
				indexed: false,
			},
			{
				name: "feeProtocol0New",
				internalType: "uint8",
				type: "uint8",
				indexed: false,
			},
			{
				name: "feeProtocol1New",
				internalType: "uint8",
				type: "uint8",
				indexed: false,
			},
		],
		name: "SetFeeProtocol",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "sender",
				internalType: "address",
				type: "address",
				indexed: true,
			},
			{
				name: "recipient",
				internalType: "address",
				type: "address",
				indexed: true,
			},
			{
				name: "amount0",
				internalType: "int256",
				type: "int256",
				indexed: false,
			},
			{
				name: "amount1",
				internalType: "int256",
				type: "int256",
				indexed: false,
			},
			{
				name: "sqrtPriceX96",
				internalType: "uint160",
				type: "uint160",
				indexed: false,
			},
			{
				name: "liquidity",
				internalType: "uint128",
				type: "uint128",
				indexed: false,
			},
			{ name: "tick", internalType: "int24", type: "int24", indexed: false },
		],
		name: "Swap",
	},
	{
		stateMutability: "nonpayable",
		type: "function",
		inputs: [
			{ name: "tickLower", internalType: "int24", type: "int24" },
			{ name: "tickUpper", internalType: "int24", type: "int24" },
			{ name: "amount", internalType: "uint128", type: "uint128" },
		],
		name: "burn",
		outputs: [
			{ name: "amount0", internalType: "uint256", type: "uint256" },
			{ name: "amount1", internalType: "uint256", type: "uint256" },
		],
	},
	{
		stateMutability: "nonpayable",
		type: "function",
		inputs: [
			{ name: "recipient", internalType: "address", type: "address" },
			{ name: "tickLower", internalType: "int24", type: "int24" },
			{ name: "tickUpper", internalType: "int24", type: "int24" },
			{ name: "amount0Requested", internalType: "uint128", type: "uint128" },
			{ name: "amount1Requested", internalType: "uint128", type: "uint128" },
		],
		name: "collect",
		outputs: [
			{ name: "amount0", internalType: "uint128", type: "uint128" },
			{ name: "amount1", internalType: "uint128", type: "uint128" },
		],
	},
	{
		stateMutability: "nonpayable",
		type: "function",
		inputs: [
			{ name: "recipient", internalType: "address", type: "address" },
			{ name: "amount0Requested", internalType: "uint128", type: "uint128" },
			{ name: "amount1Requested", internalType: "uint128", type: "uint128" },
		],
		name: "collectProtocol",
		outputs: [
			{ name: "amount0", internalType: "uint128", type: "uint128" },
			{ name: "amount1", internalType: "uint128", type: "uint128" },
		],
	},
	{
		stateMutability: "view",
		type: "function",
		inputs: [],
		name: "factory",
		outputs: [{ name: "", internalType: "address", type: "address" }],
	},
	{
		stateMutability: "view",
		type: "function",
		inputs: [],
		name: "fee",
		outputs: [{ name: "", internalType: "uint24", type: "uint24" }],
	},
	{
		stateMutability: "view",
		type: "function",
		inputs: [],
		name: "feeGrowthGlobal0X128",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
	},
	{
		stateMutability: "view",
		type: "function",
		inputs: [],
		name: "feeGrowthGlobal1X128",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
	},
	{
		stateMutability: "nonpayable",
		type: "function",
		inputs: [
			{ name: "recipient", internalType: "address", type: "address" },
			{ name: "amount0", internalType: "uint256", type: "uint256" },
			{ name: "amount1", internalType: "uint256", type: "uint256" },
			{ name: "data", internalType: "bytes", type: "bytes" },
		],
		name: "flash",
		outputs: [],
	},
	{
		stateMutability: "nonpayable",
		type: "function",
		inputs: [
			{
				name: "observationCardinalityNext",
				internalType: "uint16",
				type: "uint16",
			},
		],
		name: "increaseObservationCardinalityNext",
		outputs: [],
	},
	{
		stateMutability: "nonpayable",
		type: "function",
		inputs: [
			{ name: "sqrtPriceX96", internalType: "uint160", type: "uint160" },
		],
		name: "initialize",
		outputs: [],
	},
	{
		stateMutability: "view",
		type: "function",
		inputs: [],
		name: "liquidity",
		outputs: [{ name: "", internalType: "uint128", type: "uint128" }],
	},
	{
		stateMutability: "view",
		type: "function",
		inputs: [],
		name: "maxLiquidityPerTick",
		outputs: [{ name: "", internalType: "uint128", type: "uint128" }],
	},
	{
		stateMutability: "nonpayable",
		type: "function",
		inputs: [
			{ name: "recipient", internalType: "address", type: "address" },
			{ name: "tickLower", internalType: "int24", type: "int24" },
			{ name: "tickUpper", internalType: "int24", type: "int24" },
			{ name: "amount", internalType: "uint128", type: "uint128" },
			{ name: "data", internalType: "bytes", type: "bytes" },
		],
		name: "mint",
		outputs: [
			{ name: "amount0", internalType: "uint256", type: "uint256" },
			{ name: "amount1", internalType: "uint256", type: "uint256" },
		],
	},
	{
		stateMutability: "view",
		type: "function",
		inputs: [{ name: "", internalType: "uint256", type: "uint256" }],
		name: "observations",
		outputs: [
			{ name: "blockTimestamp", internalType: "uint32", type: "uint32" },
			{ name: "tickCumulative", internalType: "int56", type: "int56" },
			{
				name: "secondsPerLiquidityCumulativeX128",
				internalType: "uint160",
				type: "uint160",
			},
			{ name: "initialized", internalType: "bool", type: "bool" },
		],
	},
	{
		stateMutability: "view",
		type: "function",
		inputs: [
			{ name: "secondsAgos", internalType: "uint32[]", type: "uint32[]" },
		],
		name: "observe",
		outputs: [
			{ name: "tickCumulatives", internalType: "int56[]", type: "int56[]" },
			{
				name: "secondsPerLiquidityCumulativeX128s",
				internalType: "uint160[]",
				type: "uint160[]",
			},
		],
	},
	{
		stateMutability: "view",
		type: "function",
		inputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
		name: "positions",
		outputs: [
			{ name: "liquidity", internalType: "uint128", type: "uint128" },
			{
				name: "feeGrowthInside0LastX128",
				internalType: "uint256",
				type: "uint256",
			},
			{
				name: "feeGrowthInside1LastX128",
				internalType: "uint256",
				type: "uint256",
			},
			{ name: "tokensOwed0", internalType: "uint128", type: "uint128" },
			{ name: "tokensOwed1", internalType: "uint128", type: "uint128" },
		],
	},
	{
		stateMutability: "view",
		type: "function",
		inputs: [],
		name: "protocolFees",
		outputs: [
			{ name: "token0", internalType: "uint128", type: "uint128" },
			{ name: "token1", internalType: "uint128", type: "uint128" },
		],
	},
	{
		stateMutability: "nonpayable",
		type: "function",
		inputs: [
			{ name: "feeProtocol0", internalType: "uint8", type: "uint8" },
			{ name: "feeProtocol1", internalType: "uint8", type: "uint8" },
		],
		name: "setFeeProtocol",
		outputs: [],
	},
	{
		stateMutability: "view",
		type: "function",
		inputs: [],
		name: "slot0",
		outputs: [
			{ name: "sqrtPriceX96", internalType: "uint160", type: "uint160" },
			{ name: "tick", internalType: "int24", type: "int24" },
			{ name: "observationIndex", internalType: "uint16", type: "uint16" },
			{
				name: "observationCardinality",
				internalType: "uint16",
				type: "uint16",
			},
			{
				name: "observationCardinalityNext",
				internalType: "uint16",
				type: "uint16",
			},
			{ name: "feeProtocol", internalType: "uint8", type: "uint8" },
			{ name: "unlocked", internalType: "bool", type: "bool" },
		],
	},
	{
		stateMutability: "view",
		type: "function",
		inputs: [
			{ name: "tickLower", internalType: "int24", type: "int24" },
			{ name: "tickUpper", internalType: "int24", type: "int24" },
		],
		name: "snapshotCumulativesInside",
		outputs: [
			{ name: "tickCumulativeInside", internalType: "int56", type: "int56" },
			{
				name: "secondsPerLiquidityInsideX128",
				internalType: "uint160",
				type: "uint160",
			},
			{ name: "secondsInside", internalType: "uint32", type: "uint32" },
		],
	},
	{
		stateMutability: "nonpayable",
		type: "function",
		inputs: [
			{ name: "recipient", internalType: "address", type: "address" },
			{ name: "zeroForOne", internalType: "bool", type: "bool" },
			{ name: "amountSpecified", internalType: "int256", type: "int256" },
			{ name: "sqrtPriceLimitX96", internalType: "uint160", type: "uint160" },
			{ name: "data", internalType: "bytes", type: "bytes" },
		],
		name: "swap",
		outputs: [
			{ name: "amount0", internalType: "int256", type: "int256" },
			{ name: "amount1", internalType: "int256", type: "int256" },
		],
	},
	{
		stateMutability: "view",
		type: "function",
		inputs: [{ name: "", internalType: "int16", type: "int16" }],
		name: "tickBitmap",
		outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
	},
	{
		stateMutability: "view",
		type: "function",
		inputs: [],
		name: "tickSpacing",
		outputs: [{ name: "", internalType: "int24", type: "int24" }],
	},
	{
		stateMutability: "view",
		type: "function",
		inputs: [{ name: "", internalType: "int24", type: "int24" }],
		name: "ticks",
		outputs: [
			{ name: "liquidityGross", internalType: "uint128", type: "uint128" },
			{ name: "liquidityNet", internalType: "int128", type: "int128" },
			{
				name: "feeGrowthOutside0X128",
				internalType: "uint256",
				type: "uint256",
			},
			{
				name: "feeGrowthOutside1X128",
				internalType: "uint256",
				type: "uint256",
			},
			{ name: "tickCumulativeOutside", internalType: "int56", type: "int56" },
			{
				name: "secondsPerLiquidityOutsideX128",
				internalType: "uint160",
				type: "uint160",
			},
			{ name: "secondsOutside", internalType: "uint32", type: "uint32" },
			{ name: "initialized", internalType: "bool", type: "bool" },
		],
	},
	{
		stateMutability: "view",
		type: "function",
		inputs: [],
		name: "token0",
		outputs: [{ name: "", internalType: "address", type: "address" }],
	},
	{
		stateMutability: "view",
		type: "function",
		inputs: [],
		name: "token1",
		outputs: [{ name: "", internalType: "address", type: "address" }],
	},
] as const;

export const uniswapV3FactoryABI = [
	{ stateMutability: "nonpayable", type: "constructor", inputs: [] },
	{
		type: "event",
		anonymous: false,
		inputs: [
			{ name: "fee", internalType: "uint24", type: "uint24", indexed: true },
			{
				name: "tickSpacing",
				internalType: "int24",
				type: "int24",
				indexed: true,
			},
		],
		name: "FeeAmountEnabled",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "oldOwner",
				internalType: "address",
				type: "address",
				indexed: true,
			},
			{
				name: "newOwner",
				internalType: "address",
				type: "address",
				indexed: true,
			},
		],
		name: "OwnerChanged",
	},
	{
		type: "event",
		anonymous: false,
		inputs: [
			{
				name: "token0",
				internalType: "address",
				type: "address",
				indexed: true,
			},
			{
				name: "token1",
				internalType: "address",
				type: "address",
				indexed: true,
			},
			{ name: "fee", internalType: "uint24", type: "uint24", indexed: true },
			{
				name: "tickSpacing",
				internalType: "int24",
				type: "int24",
				indexed: false,
			},
			{
				name: "pool",
				internalType: "address",
				type: "address",
				indexed: false,
			},
		],
		name: "PoolCreated",
	},
	{
		stateMutability: "nonpayable",
		type: "function",
		inputs: [
			{ name: "tokenA", internalType: "address", type: "address" },
			{ name: "tokenB", internalType: "address", type: "address" },
			{ name: "fee", internalType: "uint24", type: "uint24" },
		],
		name: "createPool",
		outputs: [{ name: "pool", internalType: "address", type: "address" }],
	},
	{
		stateMutability: "nonpayable",
		type: "function",
		inputs: [
			{ name: "fee", internalType: "uint24", type: "uint24" },
			{ name: "tickSpacing", internalType: "int24", type: "int24" },
		],
		name: "enableFeeAmount",
		outputs: [],
	},
	{
		stateMutability: "view",
		type: "function",
		inputs: [{ name: "", internalType: "uint24", type: "uint24" }],
		name: "feeAmountTickSpacing",
		outputs: [{ name: "", internalType: "int24", type: "int24" }],
	},
	{
		stateMutability: "view",
		type: "function",
		inputs: [
			{ name: "", internalType: "address", type: "address" },
			{ name: "", internalType: "address", type: "address" },
			{ name: "", internalType: "uint24", type: "uint24" },
		],
		name: "getPool",
		outputs: [{ name: "", internalType: "address", type: "address" }],
	},
	{
		stateMutability: "view",
		type: "function",
		inputs: [],
		name: "owner",
		outputs: [{ name: "", internalType: "address", type: "address" }],
	},
	{
		stateMutability: "view",
		type: "function",
		inputs: [],
		name: "parameters",
		outputs: [
			{ name: "factory", internalType: "address", type: "address" },
			{ name: "token0", internalType: "address", type: "address" },
			{ name: "token1", internalType: "address", type: "address" },
			{ name: "fee", internalType: "uint24", type: "uint24" },
			{ name: "tickSpacing", internalType: "int24", type: "int24" },
		],
	},
	{
		stateMutability: "nonpayable",
		type: "function",
		inputs: [{ name: "_owner", internalType: "address", type: "address" }],
		name: "setOwner",
		outputs: [],
	},
] as const;
